language: python

git:
  depth: 2

before_install:
  - curl -L https://github.com/pyanderson/githasdiff/releases/download/1.0.4/githasdiff > ./githasdiff
  - chmod +x ./githasdiff

jobs:
  include:
    - name: "githasdiff tests"
      python: 3.8
      script: ./githasdiff githasdiff python -m unittest -v
    - name: "helloworld build and run"
      services:
        - docker
      script:
        - ./githasdiff helloworld docker build -t githasdiff:helloworld ./examples/helloworld/
        - ./githasdiff helloworld docker run githasdiff:helloworld
    - name: "hellogopher build and run"
      services:
        - docker
      script:
        - ./githasdiff hellogopher docker build -t githasdiff:hellogopher ./examples/hellogopher/
        - ./githasdiff hellogopher docker run githasdiff:hellogopher
