language: python

git:
  depth: 2

before_install:
  - sudo apt-get -y install dos2unix
  - curl -L https://raw.githubusercontent.com/pyanderson/githasdiff/master/githasdiff.py > ./githasdiff
  - dos2unix ./githasdiff
  - chmod +x ./githasdiff

addons:
  apt:
    update: true

jobs:
  include:
    - name: "githasdiff tests"
      python: 3.8
      script: ./githasdiff githasdiff python -m unittest -v
    - name: "helloworld build and run"
      services:
        - docker
      script:
        - ./githasdiff helloworld docker build -t githasdiff:helloworld ./examples/helloworld/
        - ./githasdiff helloworld docker run githasdiff:helloworld
    - name: "hellogopher build and run"
      services:
        - docker
      script:
        - ./githasdiff hellogopher docker build -t githasdiff:hellogopher ./examples/hellogopher/
        - ./githasdiff hellogopher docker run githasdiff:hellogopher
